# Generated by Django 5.1 on 2024-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='heroine',
            field=models.CharField(max_length=40),
        ),
    ]
